[platformio]
default_envs = native

[env:native]
platform = native
test_build_src = yes
build_src_filter = +<convert.cpp>
build_flags = -std=c++17 -Iinclude
test_framework = unity

[env:lilygo-t-a7670g]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.psram = enabled
lib_deps =
  https://github.com/lewisxhe/TinyGSM-fork.git
  bblanchon/ArduinoJson@^7.0.4
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^3.11.0
  https://github.com/DFRobot/DFRobot_PH.git
  https://github.com/DFRobot/DFRobot_EC10.git
  sparkfun/SparkFun MS5803-14BA Pressure Sensor@^1.1.2
build_flags =
  -DTINY_GSM_MODEM_A7670
  -DTINY_GSM_FORK_LIBRARY
  -DTINY_GSM_RX_BUFFER=1024
  -DCORE_DEBUG_LEVEL=0
  -Iinclude
